version: "3.9"

services:
  redis:
    image: redis:7
    container_name: gateway-redis
    restart: unless-stopped
    ports:
      - "${GATEWAY_REDIS_HOST_PORT:-6379}:6379"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - hishabnikash-gateway-local-network

volumes:
  redis_data:

networks:
  hishabnikash-gateway-local-network:
    name: hishabnikash-gateway-local-network
    driver: bridge
