nameOverride: identity-access

image:
  repository: 123456789012.dkr.ecr.us-east-1.amazonaws.com/erp/identity-access
  tag: nonprod-latest

containerPort: 8081

env:
  - name: SPRING_PROFILES_ACTIVE
    value: container
  - name: SERVER_PORT
    value: "8081"
  - name: DB_URL
    value: jdbc:postgresql://identity-nonprod.proxy-abcdefghijkl.us-east-1.rds.amazonaws.com:5432/identity_access_db?sslmode=require
  - name: REDIS_HOST
    value: erp-nonprod.xxxxxx.use1.cache.amazonaws.com
  - name: REDIS_PORT
    value: "6379"
  - name: SPRING_DATA_REDIS_SSL_ENABLED
    value: "true"
  - name: KAFKA_BOOTSTRAP_SERVERS
    value: b-1.erp-nonprod.xxxxxx.c2.kafka.us-east-1.amazonaws.com:9096,b-2.erp-nonprod.xxxxxx.c2.kafka.us-east-1.amazonaws.com:9096,b-3.erp-nonprod.xxxxxx.c2.kafka.us-east-1.amazonaws.com:9096
  - name: SPRING_KAFKA_PROPERTIES_SECURITY_PROTOCOL
    value: SASL_SSL
  - name: SPRING_KAFKA_PROPERTIES_SASL_MECHANISM
    value: SCRAM-SHA-512
  - name: SPRING_KAFKA_PROPERTIES_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM
    value: https
  - name: APP_SECURITY_JWT_ISSUER
    value: enterprise-platform

envFromSecrets:
  - identity-access-runtime

resources:
  requests:
    cpu: 300m
    memory: 768Mi
  limits:
    cpu: 1000m
    memory: 1536Mi

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 4
  cpuUtilizationPercentage: 70
  memoryUtilizationPercentage: 75

pdb:
  enabled: true
  minAvailable: 1

networkPolicy:
  enabled: true
  ingressNamespaces:
    - erp-gateway

externalSecret:
  enabled: true
  targetName: identity-access-runtime
  data:
    - secretKey: DB_USERNAME
      remoteKey: /erp/nonprod/identity-access/runtime
      property: DB_USERNAME
    - secretKey: DB_PASSWORD
      remoteKey: /erp/nonprod/identity-access/runtime
      property: DB_PASSWORD
    - secretKey: SPRING_DATA_REDIS_PASSWORD
      remoteKey: /erp/nonprod/identity-access/runtime
      property: SPRING_DATA_REDIS_PASSWORD
    - secretKey: APP_SECURITY_JWT_SECRET
      remoteKey: /erp/nonprod/identity-access/runtime
      property: APP_SECURITY_JWT_SECRET
    - secretKey: APP_BOOTSTRAP_ADMIN_USERNAME
      remoteKey: /erp/nonprod/identity-access/runtime
      property: APP_BOOTSTRAP_ADMIN_USERNAME
    - secretKey: APP_BOOTSTRAP_ADMIN_EMAIL
      remoteKey: /erp/nonprod/identity-access/runtime
      property: APP_BOOTSTRAP_ADMIN_EMAIL
    - secretKey: APP_BOOTSTRAP_ADMIN_PASSWORD
      remoteKey: /erp/nonprod/identity-access/runtime
      property: APP_BOOTSTRAP_ADMIN_PASSWORD
    - secretKey: APP_BOOTSTRAP_ADMIN_TENANT_ID
      remoteKey: /erp/nonprod/identity-access/runtime
      property: APP_BOOTSTRAP_ADMIN_TENANT_ID
    - secretKey: APP_BOOTSTRAP_ADMIN_DISPLAY_NAME
      remoteKey: /erp/nonprod/identity-access/runtime
      property: APP_BOOTSTRAP_ADMIN_DISPLAY_NAME
    - secretKey: SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG
      remoteKey: /erp/nonprod/identity-access/runtime
      property: SPRING_KAFKA_PROPERTIES_SASL_JAAS_CONFIG
